# Generated by Django 3.1.4 on 2021-01-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsfest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
    ]
