# Generated by Django 3.1.4 on 2021-01-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsfest', '0003_auto_20210103_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group_Participants',
            new_name='group_Registrations',
        ),
        migrations.RenameModel(
            old_name='individual_Participants',
            new_name='individual_Registrations',
        ),
    ]
